-- Quick fix to populate completed_statuses for existing orders
-- This will directly update the completed_statuses based on current workflow_status

-- First check if the column exists
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'orders' AND column_name = 'completed_statuses';

-- Update all orders with completed_statuses based on their current status
UPDATE orders 
SET completed_statuses = 
    CASE workflow_status::TEXT
        WHEN 'NEW_LEAD' THEN ARRAY[]::VARCHAR[]
        WHEN 'QUOTE_REQUESTED' THEN ARRAY['NEW_LEAD']::VARCHAR[]
        WHEN 'SITE_VISIT_SCHEDULED' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED']::VARCHAR[]
        WHEN 'SITE_VISIT_COMPLETED' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED']::VARCHAR[]
        WHEN 'QUOTE_PREPARED' THEN 
            CASE workflow_type::TEXT
                WHEN 'MATERIALS_ONLY' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED']::VARCHAR[]
                WHEN 'MATERIALS_AND_INSTALLATION' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED']::VARCHAR[]
                ELSE ARRAY['NEW_LEAD', 'QUOTE_REQUESTED']::VARCHAR[]
            END
        WHEN 'QUOTE_SENT' THEN 
            CASE workflow_type::TEXT
                WHEN 'MATERIALS_ONLY' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED']::VARCHAR[]
                WHEN 'MATERIALS_AND_INSTALLATION' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED', 'QUOTE_PREPARED']::VARCHAR[]
                ELSE ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED']::VARCHAR[]
            END
        WHEN 'QUOTE_ACCEPTED' THEN 
            CASE workflow_type::TEXT
                WHEN 'MATERIALS_ONLY' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT']::VARCHAR[]
                WHEN 'MATERIALS_AND_INSTALLATION' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED', 'QUOTE_PREPARED', 'QUOTE_SENT']::VARCHAR[]
                ELSE ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT']::VARCHAR[]
            END
        WHEN 'WORK_ORDER_CREATED' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED']::VARCHAR[]
        WHEN 'WORK_ORDER_SENT' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'WORK_ORDER_CREATED']::VARCHAR[]
        WHEN 'WORK_ORDER_SIGNED' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'WORK_ORDER_CREATED', 'WORK_ORDER_SENT']::VARCHAR[]
        WHEN 'DEPOSIT_REQUESTED' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'WORK_ORDER_CREATED', 'WORK_ORDER_SENT', 'WORK_ORDER_SIGNED']::VARCHAR[]
        WHEN 'DEPOSIT_RECEIVED' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'WORK_ORDER_CREATED', 'WORK_ORDER_SENT', 'WORK_ORDER_SIGNED', 'DEPOSIT_REQUESTED']::VARCHAR[]
        WHEN 'PO_CREATED' THEN 
            CASE workflow_type::TEXT
                WHEN 'MATERIALS_ONLY' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED']::VARCHAR[]
                WHEN 'MATERIALS_AND_INSTALLATION' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'WORK_ORDER_CREATED', 'WORK_ORDER_SENT', 'WORK_ORDER_SIGNED', 'DEPOSIT_REQUESTED', 'DEPOSIT_RECEIVED']::VARCHAR[]
                ELSE ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED']::VARCHAR[]
            END
        WHEN 'PO_SENT' THEN 
            CASE workflow_type::TEXT
                WHEN 'MATERIALS_ONLY' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'PO_CREATED']::VARCHAR[]
                WHEN 'MATERIALS_AND_INSTALLATION' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'WORK_ORDER_CREATED', 'WORK_ORDER_SENT', 'WORK_ORDER_SIGNED', 'DEPOSIT_REQUESTED', 'DEPOSIT_RECEIVED', 'PO_CREATED']::VARCHAR[]
                ELSE ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'PO_CREATED']::VARCHAR[]
            END
        WHEN 'SUPPLIER_CONFIRMED' THEN 
            CASE workflow_type::TEXT
                WHEN 'MATERIALS_ONLY' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'PO_CREATED', 'PO_SENT']::VARCHAR[]
                WHEN 'MATERIALS_AND_INSTALLATION' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'WORK_ORDER_CREATED', 'WORK_ORDER_SENT', 'WORK_ORDER_SIGNED', 'DEPOSIT_REQUESTED', 'DEPOSIT_RECEIVED', 'PO_CREATED', 'PO_SENT']::VARCHAR[]
                ELSE ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'PO_CREATED', 'PO_SENT']::VARCHAR[]
            END
        WHEN 'MATERIALS_ORDERED' THEN 
            CASE workflow_type::TEXT
                WHEN 'MATERIALS_ONLY' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'PO_CREATED', 'PO_SENT', 'SUPPLIER_CONFIRMED']::VARCHAR[]
                WHEN 'MATERIALS_AND_INSTALLATION' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'WORK_ORDER_CREATED', 'WORK_ORDER_SENT', 'WORK_ORDER_SIGNED', 'DEPOSIT_REQUESTED', 'DEPOSIT_RECEIVED', 'SUPPLIER_CONFIRMED']::VARCHAR[]
                ELSE ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'PO_CREATED', 'PO_SENT', 'SUPPLIER_CONFIRMED']::VARCHAR[]
            END
        WHEN 'MATERIALS_RECEIVED' THEN 
            CASE workflow_type::TEXT
                WHEN 'MATERIALS_ONLY' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'PO_CREATED', 'PO_SENT', 'SUPPLIER_CONFIRMED', 'MATERIALS_ORDERED']::VARCHAR[]
                WHEN 'MATERIALS_AND_INSTALLATION' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'WORK_ORDER_CREATED', 'WORK_ORDER_SENT', 'WORK_ORDER_SIGNED', 'DEPOSIT_REQUESTED', 'DEPOSIT_RECEIVED', 'MATERIALS_ORDERED']::VARCHAR[]
                ELSE ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'PO_CREATED', 'PO_SENT', 'SUPPLIER_CONFIRMED', 'MATERIALS_ORDERED']::VARCHAR[]
            END
        WHEN 'DELIVERY_SCHEDULED' THEN 
            CASE workflow_type::TEXT
                WHEN 'MATERIALS_ONLY' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'PO_CREATED', 'PO_SENT', 'SUPPLIER_CONFIRMED', 'MATERIALS_ORDERED', 'MATERIALS_RECEIVED']::VARCHAR[]
                WHEN 'MATERIALS_AND_INSTALLATION' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'WORK_ORDER_CREATED', 'WORK_ORDER_SENT', 'WORK_ORDER_SIGNED', 'DEPOSIT_REQUESTED', 'DEPOSIT_RECEIVED', 'MATERIALS_ORDERED', 'MATERIALS_RECEIVED']::VARCHAR[]
                ELSE ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'PO_CREATED', 'PO_SENT', 'SUPPLIER_CONFIRMED', 'MATERIALS_ORDERED', 'MATERIALS_RECEIVED']::VARCHAR[]
            END
        WHEN 'DELIVERED' THEN 
            CASE workflow_type::TEXT
                WHEN 'MATERIALS_ONLY' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'PO_CREATED', 'PO_SENT', 'SUPPLIER_CONFIRMED', 'MATERIALS_ORDERED', 'MATERIALS_RECEIVED', 'DELIVERY_SCHEDULED']::VARCHAR[]
                WHEN 'MATERIALS_AND_INSTALLATION' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'WORK_ORDER_CREATED', 'WORK_ORDER_SENT', 'WORK_ORDER_SIGNED', 'DEPOSIT_REQUESTED', 'DEPOSIT_RECEIVED', 'MATERIALS_ORDERED', 'MATERIALS_RECEIVED', 'DELIVERY_SCHEDULED']::VARCHAR[]
                ELSE ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'PO_CREATED', 'PO_SENT', 'SUPPLIER_CONFIRMED', 'MATERIALS_ORDERED', 'MATERIALS_RECEIVED', 'DELIVERY_SCHEDULED']::VARCHAR[]
            END
        WHEN 'PAYMENT_RECEIVED' THEN 
            CASE workflow_type::TEXT
                WHEN 'MATERIALS_ONLY' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'PO_CREATED', 'PO_SENT', 'SUPPLIER_CONFIRMED', 'MATERIALS_ORDERED', 'MATERIALS_RECEIVED', 'DELIVERY_SCHEDULED', 'DELIVERED', 'INVOICE_SENT']::VARCHAR[]
                ELSE ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'MATERIALS_ORDERED', 'MATERIALS_RECEIVED', 'DELIVERED', 'INVOICE_SENT']::VARCHAR[]
            END
        WHEN 'COMPLETED' THEN 
            CASE workflow_type::TEXT
                WHEN 'MATERIALS_ONLY' THEN ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'PO_CREATED', 'PO_SENT', 'SUPPLIER_CONFIRMED', 'MATERIALS_ORDERED', 'MATERIALS_RECEIVED', 'DELIVERY_SCHEDULED', 'DELIVERED', 'INVOICE_SENT', 'PAYMENT_RECEIVED']::VARCHAR[]
                ELSE ARRAY['NEW_LEAD', 'QUOTE_REQUESTED', 'QUOTE_PREPARED', 'QUOTE_SENT', 'QUOTE_ACCEPTED', 'MATERIALS_ORDERED', 'MATERIALS_RECEIVED', 'DELIVERED', 'PAYMENT_RECEIVED']::VARCHAR[]
            END
        ELSE ARRAY[]::VARCHAR[]
    END;

-- Show results to verify the update worked
SELECT 
    order_number,
    workflow_type::TEXT,
    workflow_status::TEXT as current_status,
    completed_statuses,
    array_length(completed_statuses, 1) as completed_count
FROM orders
WHERE workflow_status::TEXT != 'NEW_LEAD'
ORDER BY order_number
LIMIT 10;